import 'package:flutter/material.dart';
import 'package:flutterapp/taskapp/generatediphone13promax1widget/generated/GeneratedRectangleWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taskapp/generatediphone13promax1widget/generated/GeneratedRectangle618Widget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax1widget/generated/GeneratedLoginWidget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax1widget/generated/GeneratedPleaseLogintoyourexistingaccountWidget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax1widget/generated/GeneratedForgetPasswordWidget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax1widget/generated/GeneratedYourEmailWidget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax1widget/generated/GeneratedWelcomeBackWidget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax1widget/generated/GeneratedContinueWithGoogleWidget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax1widget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax1widget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax1widget/generated/GeneratedGroup1899Widget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax1widget/generated/GeneratedVectorWidget1.dart';
import 'package:flutterapp/taskapp/generatediphone13promax1widget/generated/GeneratedGroup1887Widget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax1widget/generated/GeneratedRectangle619Widget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax1widget/generated/GeneratedORWidget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax1widget/generated/GeneratedGroup1898Widget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax1widget/generated/GeneratedContinueWithMailWidget.dart';

/* Frame iPhone 13 Pro Max - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(76, 10, 1, 112),
            offset: Offset(30.0, 30.0),
            blurRadius: 35.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: LayoutBuilder(
            builder: (BuildContext context, BoxConstraints constraints) {
          return SingleChildScrollView(
            scrollDirection: Axis.vertical,
            child: Container(
                height: 926.0,
                child: Stack(children: [
                  Container(
                      width: constraints.maxWidth,
                      child: Container(
                        width: 428.0,
                        height: 926.0,
                        child: Stack(
                            fit: StackFit.expand,
                            alignment: Alignment.center,
                            overflow: Overflow.visible,
                            children: [
                              ClipRRect(
                                borderRadius: BorderRadius.zero,
                                child: Container(
                                  color: Color.fromARGB(255, 244, 250, 255),
                                ),
                              ),
                              Positioned(
                                left: 125.0,
                                top: 117.0,
                                right: null,
                                bottom: null,
                                width: 178.0,
                                height: 178.0,
                                child: GeneratedRectangleWidget(),
                              ),
                              Positioned(
                                left: 145.0,
                                top: 345.0,
                                right: null,
                                bottom: null,
                                width: 141.0,
                                height: 25.0,
                                child: GeneratedWelcomeBackWidget(),
                              ),
                              Positioned(
                                left: 81.0,
                                top: 389.0,
                                right: null,
                                bottom: null,
                                width: 268.0,
                                height: 21.0,
                                child:
                                    GeneratedPleaseLogintoyourexistingaccountWidget(),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: 0.0,
                                bottom: 0.0,
                                width: null,
                                height: null,
                                child: LayoutBuilder(builder:
                                    (BuildContext context,
                                        BoxConstraints constraints) {
                                  final double width =
                                      constraints.maxWidth * 0.7827102803738317;

                                  final double height = constraints.maxHeight *
                                      0.05075593952483801;

                                  return Stack(children: [
                                    TransformHelper.translate(
                                        x: constraints.maxWidth *
                                            0.8901869158878505,
                                        y: constraints.maxHeight *
                                            0.4946004319654428,
                                        z: 0,
                                        child: Container(
                                          width: width,
                                          height: height,
                                          child: GeneratedRectangle618Widget(),
                                        ))
                                  ]);
                                }),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: 0.0,
                                bottom: 0.0,
                                width: null,
                                height: null,
                                child: LayoutBuilder(builder:
                                    (BuildContext context,
                                        BoxConstraints constraints) {
                                  final double width =
                                      constraints.maxWidth * 0.7827102803738317;

                                  final double height = constraints.maxHeight *
                                      0.05075593952483801;

                                  return Stack(children: [
                                    TransformHelper.translate(
                                        x: constraints.maxWidth *
                                            0.8901869158878505,
                                        y: constraints.maxHeight *
                                            0.593952483801296,
                                        z: 0,
                                        child: Container(
                                          width: width,
                                          height: height,
                                          child: GeneratedRectangle619Widget(),
                                        ))
                                  ]);
                                }),
                              ),
                              Positioned(
                                left: 76.0,
                                top: 469.0,
                                right: null,
                                bottom: null,
                                width: 69.0,
                                height: 18.0,
                                child: GeneratedYourEmailWidget(),
                              ),
                              Positioned(
                                left: 76.0,
                                top: 566.0,
                                right: null,
                                bottom: null,
                                width: 67.0,
                                height: 21.0,
                                child: GeneratedPasswordWidget(),
                              ),
                              Positioned(
                                left: 164.0,
                                top: 615.0,
                                right: null,
                                bottom: null,
                                width: 101.0,
                                height: 16.0,
                                child: GeneratedForgetPasswordWidget(),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: 0.0,
                                bottom: 0.0,
                                width: null,
                                height: null,
                                child: LayoutBuilder(builder:
                                    (BuildContext context,
                                        BoxConstraints constraints) {
                                  final double width =
                                      constraints.maxWidth * 0.4742990654205608;

                                  final double height = constraints.maxHeight *
                                      0.03347733623265705;

                                  return Stack(children: [
                                    TransformHelper.translate(
                                        x: constraints.maxWidth *
                                            0.26401869158878505,
                                        y: constraints.maxHeight *
                                            0.7796976241900648,
                                        z: 0,
                                        child: Container(
                                          width: width,
                                          height: height,
                                          child: GeneratedGroup1898Widget(),
                                        ))
                                  ]);
                                }),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: 0.0,
                                bottom: 0.0,
                                width: null,
                                height: null,
                                child: LayoutBuilder(builder:
                                    (BuildContext context,
                                        BoxConstraints constraints) {
                                  final double width =
                                      constraints.maxWidth * 0.4742990654205608;

                                  final double height = constraints.maxHeight *
                                      0.03347733623265705;

                                  return Stack(children: [
                                    TransformHelper.translate(
                                        x: constraints.maxWidth *
                                            0.26401869158878505,
                                        y: constraints.maxHeight *
                                            0.8563714902807775,
                                        z: 0,
                                        child: Container(
                                          width: width,
                                          height: height,
                                          child: GeneratedGroup1899Widget(),
                                        ))
                                  ]);
                                }),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: 0.0,
                                bottom: 0.0,
                                width: null,
                                height: null,
                                child: LayoutBuilder(builder:
                                    (BuildContext context,
                                        BoxConstraints constraints) {
                                  final double width = constraints.maxWidth *
                                      0.024266463573847975;

                                  final double height = constraints.maxHeight *
                                      0.008639308855291577;

                                  return Stack(children: [
                                    TransformHelper.translate(
                                        x: constraints.maxWidth *
                                            0.3037383177570093,
                                        y: constraints.maxHeight *
                                            0.7926565874730022,
                                        z: 0,
                                        child: Container(
                                          width: width,
                                          height: height,
                                          child: GeneratedGroup1887Widget(),
                                        ))
                                  ]);
                                }),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: 0.0,
                                bottom: 0.0,
                                width: null,
                                height: null,
                                child: LayoutBuilder(builder:
                                    (BuildContext context,
                                        BoxConstraints constraints) {
                                  double percentWidth = 0.02336448598130841;
                                  double scaleX =
                                      (constraints.maxWidth * percentWidth) /
                                          10.0;

                                  double percentHeight = 0.009719222462203024;
                                  double scaleY =
                                      (constraints.maxHeight * percentHeight) /
                                          9.0;

                                  return Stack(children: [
                                    TransformHelper.translateAndScale(
                                        translateX: constraints.maxWidth *
                                            0.3037383177570093,
                                        translateY: constraints.maxHeight *
                                            0.8682505399568035,
                                        translateZ: 0,
                                        scaleX: scaleX,
                                        scaleY: scaleY,
                                        scaleZ: 1,
                                        child: GeneratedVectorWidget1())
                                  ]);
                                }),
                              ),
                              Positioned(
                                left: 153.0,
                                top: 730.0,
                                right: null,
                                bottom: null,
                                width: 124.0,
                                height: 17.0,
                                child: GeneratedContinueWithMailWidget(),
                              ),
                              Positioned(
                                left: 153.0,
                                top: 801.0,
                                right: null,
                                bottom: null,
                                width: 138.0,
                                height: 17.0,
                                child: GeneratedContinueWithGoogleWidget(),
                              ),
                              Positioned(
                                left: 207.0,
                                top: 767.0,
                                right: null,
                                bottom: null,
                                width: 19.0,
                                height: 17.0,
                                child: GeneratedORWidget(),
                              ),
                              Positioned(
                                left: 159.0,
                                top: 647.0,
                                right: null,
                                bottom: null,
                                width: 110.0,
                                height: 35.0,
                                child: GeneratedRectangle6Widget(),
                              ),
                              Positioned(
                                left: 191.0,
                                top: 654.0,
                                right: null,
                                bottom: null,
                                width: 50.0,
                                height: 26.0,
                                child: GeneratedLoginWidget(),
                              )
                            ]),
                      ))
                ])),
          );
        }),
      ),
    ));
  }
}
