import 'package:flutter/material.dart';
import 'package:flutterapp/taskapp/generatediphone13promax2widget/generated/GeneratedRectangle620Widget1.dart';
import 'package:flutterapp/taskapp/generatediphone13promax2widget/generated/GeneratedPleaseSignintoyourNewaccountWidget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax2widget/generated/GeneratedConformPasswordWidget1.dart';
import 'package:flutterapp/taskapp/generatediphone13promax2widget/generated/GeneratedRectangleWidget3.dart';
import 'package:flutterapp/taskapp/generatediphone13promax2widget/generated/GeneratedRectangle655Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taskapp/generatediphone13promax2widget/generated/GeneratedSIGNUPWidget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax2widget/generated/GeneratedYourEmailWidget2.dart';
import 'package:flutterapp/taskapp/generatediphone13promax2widget/generated/GeneratedRectangle618Widget4.dart';
import 'package:flutterapp/taskapp/generatediphone13promax2widget/generated/GeneratedRectangle619Widget5.dart';
import 'package:flutterapp/taskapp/generatediphone13promax2widget/generated/GeneratedNameWidget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax2widget/generated/GeneratedWelcomeWidget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax2widget/generated/GeneratedPasswordWidget1.dart';
import 'package:flutterapp/taskapp/generatediphone13promax2widget/generated/GeneratedRectangle619Widget6.dart';

/* Frame iPhone 13 Pro Max - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(76, 10, 1, 112),
            offset: Offset(30.0, 30.0),
            blurRadius: 35.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: LayoutBuilder(
            builder: (BuildContext context, BoxConstraints constraints) {
          return SingleChildScrollView(
            scrollDirection: Axis.vertical,
            child: Container(
                height: 926.0,
                child: Stack(children: [
                  Container(
                      width: constraints.maxWidth,
                      child: Container(
                        width: 428.0,
                        height: 926.0,
                        child: Stack(
                            fit: StackFit.expand,
                            alignment: Alignment.center,
                            overflow: Overflow.visible,
                            children: [
                              ClipRRect(
                                borderRadius: BorderRadius.zero,
                                child: Container(
                                  color: Color.fromARGB(255, 244, 250, 255),
                                ),
                              ),
                              Positioned(
                                left: 125.0,
                                top: 117.0,
                                right: null,
                                bottom: null,
                                width: 178.0,
                                height: 178.0,
                                child: GeneratedRectangleWidget3(),
                              ),
                              Positioned(
                                left: 170.0,
                                top: 345.0,
                                right: null,
                                bottom: null,
                                width: 94.0,
                                height: 28.0,
                                child: GeneratedWelcomeWidget(),
                              ),
                              Positioned(
                                left: 91.0,
                                top: 389.0,
                                right: null,
                                bottom: null,
                                width: 249.0,
                                height: 21.0,
                                child:
                                    GeneratedPleaseSignintoyourNewaccountWidget(),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: 0.0,
                                bottom: 0.0,
                                width: null,
                                height: null,
                                child: LayoutBuilder(builder:
                                    (BuildContext context,
                                        BoxConstraints constraints) {
                                  final double width =
                                      constraints.maxWidth * 0.7827102803738317;

                                  final double height = constraints.maxHeight *
                                      0.05075593952483801;

                                  return Stack(children: [
                                    TransformHelper.translate(
                                        x: constraints.maxWidth *
                                            0.8925233644859814,
                                        y: constraints.maxHeight *
                                            0.6393088552915767,
                                        z: 0,
                                        child: Container(
                                          width: width,
                                          height: height,
                                          child: GeneratedRectangle619Widget5(),
                                        ))
                                  ]);
                                }),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: 0.0,
                                bottom: 0.0,
                                width: null,
                                height: null,
                                child: LayoutBuilder(builder:
                                    (BuildContext context,
                                        BoxConstraints constraints) {
                                  final double width =
                                      constraints.maxWidth * 0.7827102803738317;

                                  final double height = constraints.maxHeight *
                                      0.05075593952483801;

                                  return Stack(children: [
                                    TransformHelper.translate(
                                        x: constraints.maxWidth *
                                            0.8925233644859814,
                                        y: constraints.maxHeight *
                                            0.7116630669546437,
                                        z: 0,
                                        child: Container(
                                          width: width,
                                          height: height,
                                          child: GeneratedRectangle619Widget6(),
                                        ))
                                  ]);
                                }),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: 0.0,
                                bottom: 0.0,
                                width: null,
                                height: null,
                                child: LayoutBuilder(builder:
                                    (BuildContext context,
                                        BoxConstraints constraints) {
                                  final double width =
                                      constraints.maxWidth * 0.7827102803738317;

                                  final double height = constraints.maxHeight *
                                      0.05075593952483801;

                                  return Stack(children: [
                                    TransformHelper.translate(
                                        x: constraints.maxWidth *
                                            0.8925233644859814,
                                        y: constraints.maxHeight *
                                            0.5669546436285097,
                                        z: 0,
                                        child: Container(
                                          width: width,
                                          height: height,
                                          child: GeneratedRectangle618Widget4(),
                                        ))
                                  ]);
                                }),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: 0.0,
                                bottom: 0.0,
                                width: null,
                                height: null,
                                child: LayoutBuilder(builder:
                                    (BuildContext context,
                                        BoxConstraints constraints) {
                                  final double width =
                                      constraints.maxWidth * 0.7827102803738317;

                                  final double height = constraints.maxHeight *
                                      0.05075593952483801;

                                  return Stack(children: [
                                    TransformHelper.translate(
                                        x: constraints.maxWidth *
                                            0.8925233644859814,
                                        y: constraints.maxHeight *
                                            0.4946004319654428,
                                        z: 0,
                                        child: Container(
                                          width: width,
                                          height: height,
                                          child: GeneratedRectangle620Widget1(),
                                        ))
                                  ]);
                                }),
                              ),
                              Positioned(
                                left: 161.0,
                                top: 756.0,
                                right: null,
                                bottom: null,
                                width: 105.0,
                                height: 35.0,
                                child: GeneratedRectangle655Widget(),
                              ),
                              Positioned(
                                left: 183.0,
                                top: 764.0,
                                right: null,
                                bottom: null,
                                width: 64.0,
                                height: 21.0,
                                child: GeneratedSIGNUPWidget(),
                              ),
                              Positioned(
                                left: 77.0,
                                top: 474.0,
                                right: null,
                                bottom: null,
                                width: 43.0,
                                height: 21.0,
                                child: GeneratedNameWidget(),
                              ),
                              Positioned(
                                left: 77.0,
                                top: 541.0,
                                right: null,
                                bottom: null,
                                width: 69.0,
                                height: 18.0,
                                child: GeneratedYourEmailWidget2(),
                              ),
                              Positioned(
                                left: 77.0,
                                top: 608.0,
                                right: null,
                                bottom: null,
                                width: 67.0,
                                height: 21.0,
                                child: GeneratedPasswordWidget1(),
                              ),
                              Positioned(
                                left: 77.0,
                                top: 675.0,
                                right: null,
                                bottom: null,
                                width: 123.0,
                                height: 18.0,
                                child: GeneratedConformPasswordWidget1(),
                              )
                            ]),
                      ))
                ])),
          );
        }),
      ),
    ));
  }
}
