import 'package:flutter/material.dart';
import 'package:flutterapp/taskapp/generatediphone13promax6widget/generated/GeneratedGroup1928Widget.dart';

/* Frame iPhone 13 Pro Max - 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedIPhone13ProMax1Widget'),
      child: Container(
        decoration: BoxDecoration(
          boxShadow: [
            BoxShadow(
              color: Color.fromARGB(76, 10, 1, 112),
              offset: Offset(30.0, 30.0),
              blurRadius: 35.0,
            )
          ],
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            return SingleChildScrollView(
              scrollDirection: Axis.vertical,
              child: Container(
                  height: 926.0,
                  child: Stack(children: [
                    Container(
                        width: constraints.maxWidth,
                        child: Container(
                          width: 428.0,
                          height: 926.0,
                          child: Stack(
                              fit: StackFit.expand,
                              alignment: Alignment.center,
                              overflow: Overflow.visible,
                              children: [
                                ClipRRect(
                                  borderRadius: BorderRadius.zero,
                                  child: Container(
                                    color: Color.fromARGB(255, 49, 141, 193),
                                  ),
                                ),
                                Positioned(
                                  left: 0.0,
                                  top: 0.0,
                                  right: null,
                                  bottom: null,
                                  width: 428.0,
                                  height: 926.0,
                                  child: GeneratedGroup1928Widget(),
                                )
                              ]),
                        ))
                  ])),
            );
          }),
        ),
      ),
    ));
  }
}
