import 'package:flutter/material.dart';
import 'package:flutterapp/taskapp/generatediphone13promax5widget/generated/GeneratedContinueWidget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax5widget/generated/GeneratedRectangleWidget1.dart';
import 'package:flutterapp/taskapp/generatediphone13promax5widget/generated/GeneratedWelcomeBackWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taskapp/generatediphone13promax5widget/generated/GeneratedYourEmailWidget1.dart';
import 'package:flutterapp/taskapp/generatediphone13promax5widget/generated/GeneratedRectangle618Widget1.dart';
import 'package:flutterapp/taskapp/generatediphone13promax5widget/generated/GeneratedPleaseEnteryourexistingaccountWidget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax5widget/generated/GeneratedRectangle6Widget1.dart';

/* Frame iPhone 13 Pro Max - 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(76, 10, 1, 112),
            offset: Offset(30.0, 30.0),
            blurRadius: 35.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: LayoutBuilder(
            builder: (BuildContext context, BoxConstraints constraints) {
          return SingleChildScrollView(
            scrollDirection: Axis.vertical,
            child: Container(
                height: 926.0,
                child: Stack(children: [
                  Container(
                      width: constraints.maxWidth,
                      child: Container(
                        width: 428.0,
                        height: 926.0,
                        child: Stack(
                            fit: StackFit.expand,
                            alignment: Alignment.center,
                            overflow: Overflow.visible,
                            children: [
                              ClipRRect(
                                borderRadius: BorderRadius.zero,
                                child: Container(
                                  color: Color.fromARGB(255, 244, 250, 255),
                                ),
                              ),
                              Positioned(
                                left: 125.0,
                                top: 117.0,
                                right: null,
                                bottom: null,
                                width: 178.0,
                                height: 178.0,
                                child: GeneratedRectangleWidget1(),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: 0.0,
                                bottom: 0.0,
                                width: null,
                                height: null,
                                child: LayoutBuilder(builder:
                                    (BuildContext context,
                                        BoxConstraints constraints) {
                                  final double width =
                                      constraints.maxWidth * 0.7827102803738317;

                                  final double height = constraints.maxHeight *
                                      0.05075593952483801;

                                  return Stack(children: [
                                    TransformHelper.translate(
                                        x: constraints.maxWidth *
                                            0.8925233644859814,
                                        y: constraints.maxHeight *
                                            0.4946004319654428,
                                        z: 0,
                                        child: Container(
                                          width: width,
                                          height: height,
                                          child: GeneratedRectangle618Widget1(),
                                        ))
                                  ]);
                                }),
                              ),
                              Positioned(
                                left: 165.0,
                                top: 555.0,
                                right: null,
                                bottom: null,
                                width: 99.0,
                                height: 35.0,
                                child: GeneratedRectangle6Widget1(),
                              ),
                              Positioned(
                                left: 145.0,
                                top: 345.0,
                                right: null,
                                bottom: null,
                                width: 141.0,
                                height: 25.0,
                                child: GeneratedWelcomeBackWidget1(),
                              ),
                              Positioned(
                                left: 92.0,
                                top: 389.0,
                                right: null,
                                bottom: null,
                                width: 247.0,
                                height: 21.0,
                                child:
                                    GeneratedPleaseEnteryourexistingaccountWidget(),
                              ),
                              Positioned(
                                left: 67.0,
                                top: 474.0,
                                right: null,
                                bottom: null,
                                width: 69.0,
                                height: 18.0,
                                child: GeneratedYourEmailWidget1(),
                              ),
                              Positioned(
                                left: 182.0,
                                top: 563.0,
                                right: null,
                                bottom: null,
                                width: 67.0,
                                height: 21.0,
                                child: GeneratedContinueWidget(),
                              )
                            ]),
                      ))
                ])),
          );
        }),
      ),
    ));
  }
}
