import 'package:flutter/material.dart';
import 'package:flutterapp/taskapp/generatediphone13promax3widget/generated/GeneratedGroup1912Widget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax3widget/generated/GeneratedGroup1877Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taskapp/generatediphone13promax3widget/generated/GeneratedSubmitWidget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax3widget/generated/GeneratedRectangle6Widget3.dart';
import 'package:flutterapp/taskapp/generatediphone13promax3widget/generated/GeneratedEnterotpcuateWidget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax3widget/generated/GeneratedOTPnotrecivedRESENDWidget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax3widget/generated/GeneratedWehavesentthecodeverificationtoYourMailIDWidget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax3widget/generated/GeneratedVerificationCodeWidget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax3widget/generated/GeneratedGroup1911Widget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax3widget/generated/GeneratedGroup1909Widget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax3widget/generated/GeneratedOTPWidget.dart';
import 'package:flutterapp/taskapp/generatediphone13promax3widget/generated/GeneratedGroup1910Widget.dart';

/* Frame iPhone 13 Pro Max - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(76, 10, 1, 112),
            offset: Offset(30.0, 30.0),
            blurRadius: 35.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: LayoutBuilder(
            builder: (BuildContext context, BoxConstraints constraints) {
          return SingleChildScrollView(
            scrollDirection: Axis.vertical,
            child: Container(
                height: 926.0,
                child: Stack(children: [
                  Container(
                      width: constraints.maxWidth,
                      child: Container(
                        width: 428.0,
                        height: 926.0,
                        child: Stack(
                            fit: StackFit.expand,
                            alignment: Alignment.center,
                            overflow: Overflow.visible,
                            children: [
                              ClipRRect(
                                borderRadius: BorderRadius.zero,
                                child: Container(
                                  color: Color.fromARGB(255, 244, 250, 255),
                                ),
                              ),
                              Positioned(
                                left: 196.0,
                                top: 80.0,
                                right: null,
                                bottom: null,
                                width: 44.0,
                                height: 28.0,
                                child: GeneratedOTPWidget(),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: 0.0,
                                bottom: 0.0,
                                width: null,
                                height: null,
                                child: LayoutBuilder(builder:
                                    (BuildContext context,
                                        BoxConstraints constraints) {
                                  final double width = constraints.maxWidth *
                                      0.03271028037383177;

                                  final double height = constraints.maxHeight *
                                      0.01511879049676026;

                                  return Stack(children: [
                                    TransformHelper.translate(
                                        x: constraints.maxWidth *
                                            0.12850467289719625,
                                        y: constraints.maxHeight *
                                            0.091792656587473,
                                        z: 0,
                                        child: Container(
                                          width: width,
                                          height: height,
                                          child: GeneratedGroup1877Widget(),
                                        ))
                                  ]);
                                }),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: 0.0,
                                bottom: 0.0,
                                width: null,
                                height: null,
                                child: LayoutBuilder(builder:
                                    (BuildContext context,
                                        BoxConstraints constraints) {
                                  final double width = constraints.maxWidth *
                                      0.45441515200606014;

                                  final double height = constraints.maxHeight *
                                      0.22089367860336798;

                                  return Stack(children: [
                                    TransformHelper.translate(
                                        x: constraints.maxWidth *
                                            0.2780373831775701,
                                        y: constraints.maxHeight *
                                            0.23002159827213822,
                                        z: 0,
                                        child: Container(
                                          width: width,
                                          height: height,
                                          child: GeneratedEnterotpcuateWidget(),
                                        ))
                                  ]);
                                }),
                              ),
                              Positioned(
                                left: 104.0,
                                top: 587.0,
                                right: null,
                                bottom: null,
                                width: 40.0,
                                height: 40.0,
                                child: GeneratedGroup1909Widget(),
                              ),
                              Positioned(
                                left: 164.0,
                                top: 587.0,
                                right: null,
                                bottom: null,
                                width: 40.0,
                                height: 40.0,
                                child: GeneratedGroup1910Widget(),
                              ),
                              Positioned(
                                left: 224.0,
                                top: 587.0,
                                right: null,
                                bottom: null,
                                width: 40.0,
                                height: 40.0,
                                child: GeneratedGroup1911Widget(),
                              ),
                              Positioned(
                                left: 284.0,
                                top: 587.0,
                                right: null,
                                bottom: null,
                                width: 40.0,
                                height: 40.0,
                                child: GeneratedGroup1912Widget(),
                              ),
                              Positioned(
                                left: 161.0,
                                top: 675.0,
                                right: null,
                                bottom: null,
                                width: 110.0,
                                height: 35.0,
                                child: GeneratedRectangle6Widget3(),
                              ),
                              Positioned(
                                left: 138.0,
                                top: 453.0,
                                right: null,
                                bottom: null,
                                width: 158.0,
                                height: 25.0,
                                child: GeneratedVerificationCodeWidget(),
                              ),
                              Positioned(
                                left: 100.0,
                                top: 501.0,
                                right: null,
                                bottom: null,
                                width: 234.0,
                                height: 34.0,
                                child:
                                    GeneratedWehavesentthecodeverificationtoYourMailIDWidget(),
                              ),
                              Positioned(
                                left: 146.0,
                                top: 646.0,
                                right: null,
                                bottom: null,
                                width: 141.0,
                                height: 16.0,
                                child: GeneratedOTPnotrecivedRESENDWidget(),
                              ),
                              Positioned(
                                left: 187.0,
                                top: 682.0,
                                right: null,
                                bottom: null,
                                width: 63.0,
                                height: 26.0,
                                child: GeneratedSubmitWidget(),
                              )
                            ]),
                      ))
                ])),
          );
        }),
      ),
    ));
  }
}
